// <auto-generated />
using System;
using CaffStore.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaffStore.Dal.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20211201124118_StoreCiffMetadata")]
    partial class StoreCiffMetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaffStore.Dal.Models.CaffFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaffRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GifRoute")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CaffFiles");
                });

            modelBuilder.Entity("CaffStore.Dal.Models.CiffFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaffFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaffFileId");

                    b.ToTable("CiffFile");
                });

            modelBuilder.Entity("CaffStore.Dal.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CaffFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaffFileId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CaffStore.Dal.Models.CiffFile", b =>
                {
                    b.HasOne("CaffStore.Dal.Models.CaffFile", "CaffFile")
                        .WithMany("CiffFiles")
                        .HasForeignKey("CaffFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("CaffStore.Dal.Models.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("CiffFileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Text")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CiffFileId", "Id");

                            b1.ToTable("Tag");

                            b1.WithOwner()
                                .HasForeignKey("CiffFileId");
                        });

                    b.Navigation("CaffFile");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("CaffStore.Dal.Models.Comment", b =>
                {
                    b.HasOne("CaffStore.Dal.Models.CaffFile", null)
                        .WithMany("Comments")
                        .HasForeignKey("CaffFileId");
                });

            modelBuilder.Entity("CaffStore.Dal.Models.CaffFile", b =>
                {
                    b.Navigation("CiffFiles");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
